### ISSUE TITLE
Can I  use MtkTelephonyAssist add SubscritionInfo of second sim card?

### ISSUE THREAD

**Issue by david-95** [nift4/MtkTelephonyAssist#1]
Hello , I use Android Doogee-vmax phone. I played with my phone ,removed a lot of mediatek packages using adb some days ago, for I felt most of its useless and waste electric power.  Everything is ok except my second sim cannot call out and send sms messages. 
I checked ,found I cannot find SubscriptionInfo for second sim card. 
I found MtkTelephonyAssist  seems have some api on sim cards states, but I don't know how to use it. I am a novice for android development. 
Could you please give me some guide? I just want using both sim cards to call and send sms. thanks in advance.

**Comment by nift4** [comment]
You should factory reset your phone, that will reinstall the missing packages. I advise against deleting random stuff you do not know what it's responsible for. Software like Universal Android Debloater also deletes too much.
